require: sudo

env:
  - RAILS_ENV=test

services:
  - docker

before_install:
  - cp config/database.sample.yml config/database.yml
  - docker-compose build

script:
  - docker-compose run app bundle exec rake db:create --rm 
  - docker-compose run app bundle exec rake db:migrate --rm 
  - docker-compose run app bundle exec rubocop --rm
  - docker-compose run app bundle exec rspec  --rm 
