require: sudo

env:
  - RAILS_ENV=test

services:
  - docker

before_install:
  - cp config/database.sample.yml config/database.yml
  - docker-compose build

script:
  - docker-compose run app bundle exec rake db:create 
  - docker-compose run app bundle exec rake db:migrate 
  - docker-compose run app bundle exec rubocop
  - docker-compose run app bundle exec rspec 
