version: '3'
volumes:  
  postgres_data: {} 
services:  
  app:    
    build:      
      context: ./studybook-api
      dockerfile: ./docker/app/DockerFile    
    depends_on:      
      - db
    volumes:
      - ./studybook-api:/app
    stdin_open: true
    tty: true
  db:    
    image: postgres    
    volumes:      
      - postgres_data:/var/lib/postgresql/data  
  web:
    restart: always    
    build:      
      context: ./nginx
      dockerfile: ./docker/web/DockerFile    
    depends_on:      
      - app    
    ports:      
      - "80:80"