version: '3'
volumes:  
  postgres_data: {} 
services: 
  web:
    restart: always    
    build:      
      context: .
      dockerfile: ./docker/web/DockerFile
    depends_on:      
      - app    
    ports:      
      - "80:80"
  app:    
    build:      
      context: .
      dockerfile: ./docker/app/DockerFile.production
    depends_on:      
      - db
    volumes:
      - ./studybook-api:/app
    ports:      
      - "3001:3001"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
  db:    
    image: postgres:11.4-alpine      
    volumes:      
      - postgres_data:/var/lib/postgresql/data  
 
